pool:
  vmImage: ubuntu-latest

steps:
  - task: Gradle@3
    displayName: Construir
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false

  - task: CopyFiles@2
    displayName: Copiar datos
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: |
        **/build/libs/*.jar
        **/build/**/*.xml
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: Publicar
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: appJar
      publishLocation: 'Container'

  - task: DownloadBuildArtifacts@0
    displayName: Descargar
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'appJar'
      downloadPath: '$(Pipeline.Workspace)'


  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'rodrigorubilarklagges'
      projectKey: 'microservicio-spring'
      projectName: 'microservicio-spring'
      extraProperties: |
        sonar.coverage.devops.xmlReportPaths=$(Pipeline.Workspace)/appJar/build/reports/devops/test/devopsTestReport.xml
    displayName: 'Preparar Sonarqube'

  - task: Gradle@3
    displayName: 'Analizar'
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: "build"
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: true
      sqGradlePluginVersionChoice: 'specify'
      sonarQubeGradlePluginVersion: '2.6.1'

  - task: SonarCloudPublish@1
    displayName: 'Publicar resultados'
    inputs:
      pollingTimeoutSec: '300'

